var lw_lang_en ={
    ID_NUMBER_INVALID:"Phone Number Not Valid!",
	ID_NUMBER_EMPTY:"Phone Number Empty!",
    ID_ADDSEARCH1:"Can't find",
    ID_ADDSEARCH2:"in the list",
    ID_SEARCH_ABOUT:"Search about",
    ID_SEARCH_KEYWORD:"Searching Keywords can't include \"space\"!",
    ID_UPLOAD_FILE:"Upload File",
    ID_UPLOAD_IMAGE:"Upload Image",       
    ID_UPLOADING:"File uploading",
    ID_IMAGE_LIMITED:"Image size 1M limited!",
    ID_FILE_FAILED:"File Load Failed!",
    ID_PREVIEW:"Preview",
    ID_UPLOAD_SUCCESS:"Upload Success",
    ID_FILEUP:'Upload files to Cloud Disk',
    ID_UPLOAD_FAILED:'Upload Failed',
    ID_LOADING:"Loading",
    ID_IMAGE_LOADING:"Image loading",
    ID_CLOSE:"Close",
    ID_PRE_IMAGE:"Pre Image",
    ID_NEXT_IMAGE:"Next Image",
    ID_FIRST_IMAGE:"First Image",
    ID_FINAL_IMAGE:"Final Image",
    ID_DESCRIBTION:"Describtion",
    ID_INNITIALIZING_FAILED:"Innitializing failed.",
    ID_SEPERATED:"phone Number/Name(;)",
    ID_SMS_CONTENT:"SMS Content",
    ID_BUSY_LOGIN:"Server busy, login again please!",
    ID_LOGIN_FIRST:"Login please!",
    ID_AT_DEPARTMENT:"@Department",
    ID_DELETE_MEMBER:"Delete member",
    ID_DELETE_SUCCESS:"Delete success!",
    ID_RESTORE_SUCCESS:"Restore success!",
    ID_SERVER_BUSY:"Server busy, please try later!",
    ID_ADD_ECTERNAL:"Add to External Contacts Group",
    ID_ADD_MEMBER:"Add member",
    ID_MODIFY_MEMBER:"Change member info",
    ID_CHANGE_GROUPNAME:"Change Group Name",
    ID_GROUP_INCLUDED:"This Group is existed,please try another?",
    ID_INPUT_GROUPNAME:"Input Group Name/Can't same with other Group",
    ID_CHANGE_SUCCESS:"Change Success!",
    ID_GROUPNAME_EMPTY:"Group Name can't empoty and can't include \"space\"!",
    ID_DELETE_GROUP:"Delete the Group",
    ID_SURE_DELETEGROUP:"Delete the Group?",
    ID_DONE:"Done",
    ID_NEWGROUP:"New Group",
    ID_OK:"OK",
	ID_CANCEL:'Cancel',
    ID_SEARCH_NAME:"Searching by Name",
    ID_ADD_GROUPMEMBER:"Add Group member",
    ID_TALKING_H:"Talking with",
    ID_PEER_RINGING:" is ringing",
    ID_TALKING_F:"",
    ID_CALL_END:"Callee Hookon",
    ID_CALLING_TO:"Calling to",
    ID_CALLED_NUM:"No Called Number",
    ID_WRONG_NUM:"Wrong Number,Please check",
    ID_FAILTOCALLSELF:"Can't call Self",
    ID_CALLEE_OFFLINE:"Callee offline,please try normal call!",
    ID_WHO_CALL:"Who do you want call?",
    ID_SEARCH_CAONTACTS:"Search/Contacts",
    ID_SMS_MISSED:"SMS Content Missed!",
    ID_RECNUM_MISSED:"Receiving Number Missed!",
    ID_WRONGNUM:"Wrong Number,Please check!",
    ID_WRONG_GROUPNAME:"Wrong Group Name:",
    ID_NUM_MISSED:"Their Phone Number Missed!",
    ID_NUM_WRONG:"Their Phone Number Wrong!",
    ID_CONFIRM:"Please Confirm",
    ID_CONFIRM_SEND:"Whether to ignore these recipients and continue to send?",
    ID_IGNORE:"Yes,Ignore",
    ID_CHANGE_AGAIN:"No,I'll change again",
    ID_SEND_FAILED:"Send failed,please check phone number!",
    ID_FROM:"From",
    ID_SEND_SUCCESS:"Send success!",
    ID_SMSCONTENT:"SMS Content:",    
    ID_RECEIVER:"Receiver:",
    ID_SEND_TIME:"Send Time:",
    ID_RESEND:"Resend",
    ID_SMS_RECORD:"No SMS records!",
    ID_TWO_OPTIONS:"Two options at least!",
    ID_QUESTION:"Question",
    ID_TAGS:"Tag for searching later, up to 5 tags,seperated by \"space\"",
	ID_TAG_BT:'Tags: ',
    ID_TAG_SEPERATED:"Tag: Up to 5 tags and seperated by \"space\"",
    ID_OPTION:"Option",
    ID_CANNOT_SEND:"etc. Cannot send message, due to mobile number doesn’t registered!",
    ID_SMS_NOTICE:"SMS notification",
    ID_SMS_REMIND:"Do you need to remind your offline colleague to check this task?",
    ID_REMIND:"Remind",
    ID_ADD_TAG:"Add a tag on your favorite",
    ID_TAG_MANAGEMENT:"Edit tag",
    ID_FAVORITE_REMOVE:"Remove Favorite",
    ID_ADD_FAVORITE:"Add to favorite",
    ID_UNTAGGED:"Untagged",
    ID_TAG:"Tag it",
    ID_IF_REMOVETAG:"Are you sure to remove this tag?",
    ID_DELETETAG_NOTE:"The tagged message won’t be deleted when you remove tag.",
    ID_TAG_EMPTY:"Tag area could not be empty",
    ID_EXIT:"Exit",
    ID_MANAGE_TAG:"Manage tag",
    ID_REMOVE_FAVORITE:"Please remove favorite attention before you delete this message.",
    ID_RESTORED:"Restored",
    ID_RECYCLE_EMPTY:"Your recycle bin has been empty.",
    ID_DELETE_NOTE1:"Are you sure to delete this message permanently?",
    ID_DELETE_NOTE2:"This message would be permanently deleted.",
    ID_PERMANENTLY_DELETE:"Deleted!",
    ID_RECYCLE_NOTE1:"Permanently deleted",
    ID_RECYCLE_NOTE2:"Are you sure to clean recycle bin?",
    ID_RECYCLE_NOTE3:"All messages would be permanently deleted.",
    ID_RECYCLE_NOTE4:"All messages have been permanently deleted.",
    ID_RECYCLE_NOTE5:"Restore",
    ID_SERVICE_UNAVAILABLE:"Service is currently unavailable, please try it later",
    ID_MVIDEO_INAVAILABLE:"Failed to initiate a video conference.",
    ID_ENTER_FAILED:"Failed to enter the conference.",
    ID_FAVORITE_NOTE:"You haven’t added any task and weibo to favorite yet. For important task and weibo, please add to favorite for attention.",
    ID_PREVIOUS_READ:"Your previous read",
    ID_NO_CONTENT:"No current content",
    ID_CHECK_DIALOGUE:"Check dialogue",
    ID_REPLY:"Reply",
    ID_REPLYALL:"Reply all",
    ID_WITH_SRC:'with source',
    ID_NO_NEWREPLY:"No new reply",
    ID_USER_REMOVED:"This user has been removed",
    ID_REMARK_COMPLETED:"Remark task completed",
    ID_DOWNLOAD_FILE:"Download file",
    ID_DOWNLOAD:"Download",
    ID_DELETE_MESSAGE:"Delete this message",
    ID_CLOUD_SAVE:"Attachment file has been saved in cloud disk.",
    ID_ATTACHED:"Attachment",
    ID_MOVETOCLOUD:"Move to cloud disk",
    ID_SHARE_CLOUD:"Share files from cloud disk",
    ID_ORIGINAL_PIC:"View original picture",
    ID_PACKUP:"Close",
    ID_VIEW_RESULT:"View result",
    ID_PREVIEW:"Preview",
    ID_DELETE_FILE:"Are you sure to delete this file?",
    ID_DELETE_TIP:"If you delete this file, your staff can not download the file.",
    ID_SHARE_WEIBO:"Share to weibo",
    ID_SHARE_LWORK:"Share to team collaboration",
    ID_WORD_REMAIN:"</span><span class=\"maxNum\">300</span><span> character remaining.",
    ID_SHARE_CLOUD:"Share files from cloud disk, please download for view.",
    ID_FAVORITE_DONE:"Add to favorite",
    ID_FAVORITE_TIME:'Data:',
    ID_TAGNAME_NOTE:"Tag name cannot more than 24 characters, you can select from existed tag name.",
    ID_TAGGED:"Tagged successful",
    ID_TAG_NOTE:"Tag cannot be empty.",
    ID_FAV_NOTE:"Are you sure to remove favorite",
    ID_FAV_NOTE_TIP:"Remove favorite does not delete the message",    
    ID_TASK_DONE:"Task has been read",
    ID_ATTEND_VOTE:"attend vote",
    ID_SET_COMPLETE:"set this task as completed task",
    ID_INVITE:"Invited",
    ID_INVITE1:"Invite",
    ID_UNKNOWN:"Unknown",
    ID_SHARE:"Share",
    ID_ANSWER:"Answer",
    ID_TRACE:"Follow",
    ID_NO_NEWUPDATE:"No new status update",
    ID_INVITATION:"The invitation has been delivered",
    ID_SELECT_INVITE:"Please select invite people!",
    ID_LWORK_PLATFORM:"LWORK platform",
    ID_MESS_ATT:"Message reminding",
    ID_ON_LWORK:"On Lwork platform",
    ID_LWORK_PLATFORM:"LWORK platform",
    ID_NEW_MESSAGE_HEADER:"【you have",
    ID_NEW_MESSAGE_CON:"new message】",
    ID_MESSAGE_NOTE:"Note:",
    ID_MESSAGE_NOTEMSG:"You have new message from Lwork!", 
    ID_WEBIM_NOTEMSG:"New instant message from ",
    ID_VIDEO_INVITE:"'s multi-part video",
    ID_VIDEO_P2PINVITE:"'s video call",
    ID_ADD_EMPTYGROUP:"This group is empty, please add member ",
    ID_SETTING:"My Profile",
    ID_CHANGE_PASSWORD:"Change Password",
    ID_CHANGE_PIC:"Change Picture",
    ID_UPLOAD_PIC:"Upload picture",
    ID_NUM_INPUT:"Please input a valid phone number, country code is essential, such as 0086 for China. ",
    ID_EMAIL:"Please input a valid email address",
    ID_SUCCESSFUL:"Change successful",
    ID_SEND_SUCCESSFUL:'Send successful',
    ID_ORG_PASSWORD:"Original password could not be empty",
    ID_NEW_PASSWORD:"New password could not be empty",
    ID_PASSWORD_LENGTH:"Password length could not less 6 letters/number/symbol ",
    ID_PSWD_MATCH:"Password doesn't match",
    ID_ORGPSWD_ERR:"Original password error",
    ID_CONFIRM_COMPLETE:"Confirm complete this task as ‘done’",
    ID_INFORM_TASK:"Inform all task member when set this task done",
    ID_DONETASK:"This task has been done",
    ID_SELETE_OPTION:"Please select the options",
    ID_VOTE_COMPLETE:"Vote complete, click to view vote result!",
    ID_REFRESH_VOTE:"Refresh vote result",
    ID_REPLY_SUCCESS:"Reply successful!",
	ID_REPLY_FAILED:'Reply Failed!',
    ID_UPDATE_TIME:"Latest update time ",
    ID_NO_RESULT:"There is no result to display",
    ID_CURRENT_FILE:"Current file",
    ID_MODERATOR:"Moderator",
    ID_SET_MODERATOR:"Set as moderator",
    ID_CONNECTING:"Connecting",
    ID_HANG_UP:"Hang Up",
    ID_HANGUP_NOTE:"Are you sure to hang up the phone?",
    ID_ATTENDEE:"Attendee",
    ID_MEETING_TOPIC:"Meeting Topic: new meeting",
    ID_NEW_MEETING:"New Meeting",
    ID_MEETING_PERIOD:"Meeting Period",
    ID_RESTART:"Restart",
    ID_ENTER_NUM:"Phone number/ Characters ",
    ID_CALL_NOTE:"Minimum attendee could not less than 2 ",
    ID_TOPIC:"Meeting topic:",
    ID_JOIN_WEIBO:"to join this weibo",
    ID_WEIBO:"Weibo",
    ID_ONLINE:"Online",
    ID_OFFLINE:"Offline",
    ID_REDAIL:"Redail",
    ID_FILENAME:"Filename",
    ID_CO_WORK:"Tasks",
    ID_VOTE:"Ballot",
    ID_FILE:"Files",
    ID_CONFERENCE_CALL:"Voice Conference",
    ID_QA:"Q&A",
    ID_BALLOT:"ballot",
    ID_VIDEOCALL:"Video call",
    ID_TICKET:"ticket",
    ID_VOTED:"Voted",
    ID_NAME:"Name:",
    ID_EMPLOYEE_NO:"Staffid:",
    ID_DEPT:"Department:",
    ID_EMAIL2:"E-Mail:", 
    ID_PHONE_MOBILE:"Mobile Number:",
    ID_PHONE_PSTN:"Pstn Number:",
    ID_PHONE_EXTENSION:"Ext Number:",
    ID_PHONE_OTHER:"Other Number:",
    ID_PHONE_CHOICE:"Please Choice Number",
    ID_DELETE:"Delete",
	ID_CHOOSEFile:'Choose File',
    ID_TAKE_WORK:"Team Collaboration",
    ID_TAKE_WEIBO:'Enterprise Weibo',    
    ID_TAKE_VOTE:'Poll',       
    ID_MAKE_CONF:'Web Video',   
    ID_TEXTING:'Web SMS',   
    ID_VOIP:'Web Call',
    ID_FORUM_TITLE:'Subject',  
    ID_FORUM_CONTENT:'Content',
    ID_FORUM_REPLY:'Write a reply...',
	ID_FORUM_SUCCESS:"Send success!",
	ID_SEARCH_TIP: '+ Add people to notify',
    ID_CHARACTER_LEFT:"You can only enter",
    ID_CHARACTER_EXCEED:"Exceed",
    ID_CONFORUM_TIP:'What’s your question?',
    ID_SUBFORUM_TIP:'Subject (Less than 200 words)',
    ID_VIDEO_FREE:'Free',
    ID_POLLSITEM_IMG:'/images/update_pic_en.png',
    ID_SEARCH_FOR:'Search about',
    ID_SEARCH_ABOUT:'for',  
    ID_UPLOAD_TIP:'File size 10M limited, Large files can share by Cloud disk!',
    ID_FORUM_POST:'Post',
    ID_FORUM_FORUMS:'Forums',
    ID_CREATE_GRUOP:"You can't leave this empty.",
    ID_GETMICRO_WRONG:'Your microphone is not working or is hardware-muted!',
    ID_VIDEO_TIP:'You have an unfinished conference from ',   
    ID_VIDEO_CONNECTIP:'Do you want re-enter this conference?',
    ID_VIDEO_RECONNECT:'re-enter',
    ID_VIDEO_USER: 'This user has been invited.', 
    ID_VIDEO_OFFLINE: "This user is currently offline, not available.", 
    ID_VIDEO_ROOM: 'The room is full.',
    ID_VIDEO_Moder: "Only moderator could invite participant.",
    ID_VIDEO_END: 'The conference is end.', 
    ID_VIDEO_EXIT: 'You have leave the conference.',
    ID_VIDEO_WAIT:'waiting...',
    ID_P2PVIDEO_FAILED:'Failed to initiate a video call.',
    ID_P2PVIDEO_ANSWER_FAILED:'Failed to answer the video call.',
    ID_P2PVIDEO_ADD_PEER_FIRST:'You should add a peer before initiating the video call.',
    ID_P2PVIDEO_OVER:'Video call is over.',
    ID_P2PVIDEO_TOO_MANY_PEERS: 'You can NOT add more than one peer in a video call.',
    ID_P2PVIDEO_PEER_REJECTED: 'Peer rejected.',
    ID_P2PVIDEO_PEER_HOOKON:'Peer terminated the video call.',
    ID_TASKS_SHORTMSG:'This tasks contains ',
    ID_TASKS_LOGIN:'. Please view by mobile app.' ,
    ID_TASKS_CONTAINERIMG: 'images',  
    ID_TASKS_CONTAINERATTACHE: 'attachment',
    ID_REPLY_DIALOG:' View dialogue',
    ID_FAVORITE_ALL:'All',
    ID_VIDEO_ALLOWINVITE:'Inviting',   
    ID_VIDEO_JOIN:'join the conference?',   
    ID_VIDEO_ALLOW:'Accept',
    ID_VIDEO_DENY:'Reject',
    ID_VIDEO_CONFIRM:'Inviting Confirm',
    ID_VIDEO_INVITED1:'Video conference invitation from',
    ID_VIDEO_INVITED2:'Do you accept to <em>end</em> current conference to join it?',
    ID_VIDEO_INVITED3:'Do you accept to <em>quit</em> current conference to join it?',
    ID_VIDEO_INVITED4:'',
    ID_VIDEO_INVITED5:'Video call from ',
    ID_VIDEO_INVITED6:'',
    ID_VIDEO_INVITED7:'Do you accept to <em>end</em> current video call to join it?',
    ID_ADDGROUP_SUCCESS:'Successful',
    ID_EXT_CONTANTS:'External Contacts',
    ID_EXT_ACCOUNT:'Account@Company ID',   
    ID_EXT_PHONE:'Phone number',  
    ID_EXT_EMAIL:'Email address',      
    ID_EXT_ADDED:'This member is existed,please try another?', 
    ID_EXT_SUCCESS:'Has been added', 
    ID_EXT_ADDNUM:'external contacts', 
    ID_EXT_DIALOGTITLE:'Adding or modifying external contacts info',
    ID_VOICE_PHONE:'Please input a valid phone number.',
    ID_NOTI_TITLE:'Desktop Notification',
    ID_NOTI_BTN1:'Yes',
    ID_NOTI_BTN2:'No,thanks',
    ID_NOTI_BTN3:'Close',
    ID_NOTI_QUS:'Do you need Lwork desktop notification?',           
    ID_NOTI_ICON:'Click icon on address bar.', 
    ID_NOTI_SELECT:'Select: notification - Always allow on this site', 
    ID_NOTI_TIP:'Showing instant notification when you have new message and invitation.',  
    ID_IM_START_IM:'Send instant message.',
    ID_IM_VIEW_MY_IM:'View instant messages.',
    ID_IM_CREATE_SESSION_FAILED:'Failed to create session.',
    ID_IM_I_INVITE:'I invited ',
    ID_IM_TO_JOIN_CHAT:' to join the chat.',
    ID_IM_ALREADY_IN_SESSION:' already in the session.',
    ID_IM_CANT_INVITE_OFFLINES:'You can NOT invite offline user.',
    ID_IM_I_QUITED:'I quited.',
    ID_IM_CHATROOM:'Session',
    ID_IM_SEND_MSG:'Send',
    ID_IM_DIRECT_SEND_TIP:'Enter: To Send',
    ID_MAIL_CC:'cc',
    ID_MAIL_SENDER:'sender',
    ID_MAIL_RECEIVER:'receiver',
    ID_MAIL_LOADING_MAIL_FAILED: 'fail to loading mail with network reason',
    ID_MAIL_LOADING:"loading mail content, please wait...",
    ID_MAIL_FETCH_LIST:"hunting mail list",
    ID_MAIL_LOGIN_SUCCESS:'succeed to login mail server',
    ID_MAIL_LOGIN_FAIL:'fail to login mail server',
    ID_MAIL_LOGINING:'logining mail server',
    ID_MAIL_SET_TIP:'please logining first',
    ID_MAIL_TRANSFER_ONLY_ONE:"only one mail can be selected",
    ID_MAIL_NEW:'new mail',
    ID_MAIL_NO_RECEIVER:'no receiver',
    ID_MAIL_ATTACH_UPLOADING:'uploading attachment, please wait',
    ID_MAIL_RECEIVER_TIP:'input receiver address(seperated by ";")',
    ID_MAIL_SENDING:'sending...',
    ID_MAIL_SENT_FAIL_REASON:'fail to send mail,reason:',
    ID_MAIL_SENT_SUCCESS:'succeed to send mail',
    ID_MAIL_CLOSE_NEW:'save？',
    ID_MAIL_CLOSE_NEW_TIP:"this email will be close, do you want to save to draft box?",
    ID_REQUEST_ERROR:'Server is busy,try again later!',
    ID_WRONG_VOIP:'Please click the "Allow" button above.',
    ID_ERROR_PERMISSION:'No permission.',
    ID_ERROR_NOBLANCE:'Insufficient balance.', 
    ID_ERROR_COMNOBLANCE:'Insufficient balance.', 
    ID_ERROR_NORESOURCE:'Insufficient conference resource, please try it later.',
     ID_PREPAR_CALL:'Preparing to call...' 
};
var lw_lang_ch = {
    ID_NUMBER_INVALID:"请选择有效的电话号码!",
	ID_NUMBER_EMPTY:"没有登记电话号码!",
    ID_ADDSEARCH1:"通讯录中没有",
    ID_ADDSEARCH2:"相关同事",
    ID_SEARCH_ABOUT:"搜索相关的",
    ID_SEARCH_KEYWORD:"搜索关键字不能包含空格！",
    ID_UPLOAD_FILE:"上传附件",
    ID_UPLOAD_IMAGE:"上传图片",    
    ID_UPLOADING:"文件正在上传...",
    ID_IMAGE_LIMITED:"请上传不超过1M图片文件！",
    ID_FILE_FAILED:"文件传送失败！",
    ID_PREVIEW:"预览",
    ID_UPLOAD_SUCCESS:"上传成功", 
    ID_FILEUP:'上传文件到我的网盘',
    ID_LOADING:"加载中...",
    ID_IMAGE_LOADING:"图片加载中...",
    ID_CLOSE:"关闭",
    ID_PRE_IMAGE:"查看上一张图片",
    ID_NEXT_IMAGE:"查看下一张图片",
    ID_FIRST_IMAGE:"这是第一张图片",
    ID_FINAL_IMAGE:"这是最后一张图片",
    ID_DESCRIBTION:"详细描述",
    ID_INNITIALIZING_FAILED:"初始化失败。",
    ID_SEPERATED:"号码/同事/群组(;)",
    ID_SMS_CONTENT:"输入短信内容",
    ID_BUSY_LOGIN:"服务器繁忙，请重新登录！",
    ID_LOGIN_FIRST:"请您先登录！",
    ID_AT_DEPARTMENT:"@该部门",
    ID_DELETE_MEMBER:"删除成员",
    ID_DELETE_SUCCESS:"删除成功！",
    ID_RESTORE_SUCCESS:"恢复成功!",
    ID_SERVER_BUSY:"服务器繁忙，请稍后再试！",
    ID_ADD_ECTERNAL:"增加到外部联系人",
    ID_ADD_MEMBER:"添加成员",
    ID_MODIFY_MEMBER:"修改成员信息",
    ID_CHANGE_GROUPNAME:"修改组名",
    ID_GROUP_INCLUDED:"已包含该组",
    ID_INPUT_GROUPNAME:"输入组名/不能与现有的组重复",
    ID_CHANGE_SUCCESS:"修改成功！",
    ID_GROUPNAME_EMPTY:"组名不能包含空格和为空",
    ID_DELETE_GROUP:"删除该组",
    ID_SURE_DELETEGROUP:"您确定要删除该组吗？",
    ID_DONE:"完成",
    ID_NEWGROUP:"新建组",
    ID_OK:"确定",
	ID_CANCEL:'取消',
    ID_SEARCH_NAME:"通过拼音或汉字搜索添加成员",
    ID_ADD_GROUPMEMBER:"增加群组成员",
    ID_TALKING_H:"与",
    ID_PEER_RINGING:"正在振铃",
    ID_TALKING_F:'通话中',
    ID_CALL_END:"对端已挂机",
    ID_CALLING_TO:"正在呼叫",
    ID_CALLED_NUM:"请填写被叫号码",
    ID_WRONG_NUM:"所填号码有误，请重新填写",
    ID_FAILTOCALLSELF:"不能给自己发起视频",
    ID_CALLEE_OFFLINE:"对方不在线，不能发起视频，还是电话沟通吧！",
    ID_WHO_CALL:"向谁发起视频呢？",
    ID_SEARCH_CAONTACTS:"搜索/右边选择联系人",
    ID_SMS_MISSED:"短信内容不能为空！",
    ID_RECNUM_MISSED:"接收者手机号码不能为空！",
    ID_WRONGNUM:"你填写的短信接收者不对，请核对后再发送！",
    ID_WRONG_GROUPNAME:"下面的群组名不对：",
    ID_NUM_MISSED:"下面的群组用户没有登记电话号码：",
    ID_NUM_WRONG:"下面的接收者/电话号码不对：",
    ID_CONFIRM:"请确认",
    ID_CONFIRM_SEND:"是否忽略这些接收者并继续发送？",    
    ID_IGNORE:"是，忽略",
    ID_CHANGE_AGAIN:"否，我再改一下",
    ID_SEND_FAILED:"的发送失败了，请确认这些接收号码的正确性！",
    ID_FROM:"来自:",
    ID_SEND_SUCCESS:"短信已发送成功！",
    ID_SMSCONTENT:"短信内容： ",
    ID_RECEIVER:"发送对象：",
    ID_SEND_TIME:"发送时间",
    ID_RESEND:"重新发送",
    ID_SMS_RECORD:"没有已发送短信记录！",
    ID_TWO_OPTIONS:"集体决策不能少于两个选项！",
    ID_QUESTION:"问题",
	ID_TAG_BT:'标签：',
    ID_TAGS:"打个标签便于今后查找，可以设置5个标签，空格分开",
    ID_TAG_SEPERATED:"标签：最多5个标签，用空格",
    ID_OPTION:"选项",
    ID_CANNOT_SEND:"等没有登记手机号，不能向其发送！",
    ID_SMS_NOTICE:"短信提醒",
    ID_SMS_REMIND:"是否需要短信提醒不在线同事查收这条任务？",
    ID_REMIND:"提醒",
    ID_ADD_TAG:"给你的关注加个标签吧，可以更方便查看关注哦！",
    ID_TAG_MANAGEMENT:"管理标签",
    ID_FAVORITE_REMOVE:"取消关注",
    ID_ADD_FAVORITE:"关注",
    ID_UNTAGGED:"未加标签",
    ID_TAG:"加标签",
    ID_IF_REMOVETAG:"你确定要删除当前标签吗?",
    ID_DELETETAG_NOTE:"删除标签不会把具有该标签的消息从关注中删除。",
    ID_TAG_EMPTY:"标签不能为空！",
    ID_EXIT:"退出管理",
    ID_MANAGE_TAG:"管理标签",
    ID_REMOVE_FAVORITE:"删除之前请先取消关注！",
    ID_RESTORED:"已恢复！",
    ID_RECYCLE_EMPTY:"您的回收站已清空",
    ID_DELETE_NOTE1:"你确认要永久删除这条消息吗？",
    ID_DELETE_NOTE2:"永久删除后将无法查看该消息。",
    ID_PERMANENTLY_DELETE:"已永久删除！",
    ID_RECYCLE_NOTE1:"永久刪除", 
    ID_RECYCLE_NOTE2:"你确认要清空回收站吗？", 
    ID_RECYCLE_NOTE3:"清空回收站将永久删除这些消息。",
    ID_RECYCLE_NOTE4:"所有消息已永久删除！",
    ID_RECYCLE_NOTE5:"恢復",
    ID_SERVICE_UNAVAILABLE:"服务器繁忙，请稍后再试！",
    ID_MVIDEO_INAVAILABLE:"发起视频失败！",
    ID_ENTER_FAILED:"加入视频会议失败！",
    ID_FAVORITE_NOTE:"你还没有关注任何微博和任务呢！ 对于重要的微博或者任务，赶紧关注一下哦！",
    ID_PREVIOUS_READ:"之前看到这里了哟~",
    ID_NO_CONTENT:"您当前没有任何内容",
    ID_CHECK_DIALOGUE:"查看对话",
    ID_REPLY:"回复",
    ID_REPLYALL:"回复所有人",
    ID_WITH_SRC:'带原文',
    ID_NO_NEWREPLY:"您当前没有新回复",
    ID_USER_REMOVED:"该员工已删除",
    ID_REMARK_COMPLETED:"标记完成",
    ID_DOWNLOAD_FILE:"文件下载",
    ID_DOWNLOAD:"下载",
    ID_DELETE_MESSAGE:"删除此消息",
    ID_CLOUD_SAVE:"已经将附件保存到网盘！",
    ID_ATTACHED:"附件",
    ID_MOVETOCLOUD:"转到网盘",
    ID_SHARE_CLOUD:"通过网盘分享文件：",
    ID_ORIGINAL_PIC:"查看原图",
    ID_PACKUP:"收起",
    ID_VIEW_RESULT:"查看结果",
    ID_PREVIEW:"预览",
    ID_DELETE_FILE:"你确定要删除这个文件吗？",
    ID_DELETE_TIP:"文件删除后会造成你之前共享的同事不能下载该文件。",
    ID_SHARE_WEIBO:"分享到企业微博",
    ID_SHARE_LWORK:"分享到工作协同",
    ID_WORD_REMAIN:"还能输入</span><span class=\"maxNum\">300</span><span>个字",
    ID_SHARE_CLOUD:"通过网盘分享文件，下载下来看看吧~",
    ID_FAVORITE_DONE:"添加关注成功！",
    ID_FAVORITE_TIME:'关注时间：',
    ID_TAGNAME_NOTE:"标签1~12个字，不能有空格，可以已有标签中选择：",
    ID_TAGGED:"打标签成功！",
    ID_TAG_NOTE:"标签不能为空！",
    ID_FAV_NOTE:"你确定要取消关注吗？",
    ID_FAV_NOTE_TIP:"取消关注不会删除该消息。",  
    ID_TASK_DONE:"阅读了该任务",
    ID_ATTEND_VOTE:"参与了投票",
    ID_SET_COMPLETE:"将该任务状态设置为完成",
    ID_INVITE:"邀请了 ",
    ID_INVITE1:"邀请",
    ID_UNKNOWN:"未知",
    ID_SHARE:"分享",
    ID_ANSWER:"回答",
    ID_TRACE:"动态",
    ID_NO_NEWUPDATE:"当前没有任何动态！",
    ID_INVITATION:"已发送您的邀请！",
    ID_SELECT_INVITE:"请选择邀请人！",
    ID_LWORK_PLATFORM:"WEB网关",
    ID_MESS_ATT:"消息提醒",
    ID_ON_LWORK:"在Lwork工作平台，",
    ID_NEW_MESSAGE_HEADER:"【您有",
    ID_NEW_MESSAGE_CON:"条新消息】",
  //  ID_NEW_MESSAGE:"【 您有\" + num + \"条新消息 】 - ", 
    ID_MESSAGE_NOTE:"消息提醒:",
	ID_MESSAGE_NOTEMSG:"您在Lwork工作平台有新消息",
    ID_WEBIM_NOTEMSG:"您有新的即时消息,来自",
    ID_VIDEO_INVITE:"邀请您参加多方视频",
    ID_VIDEO_P2PINVITE:"邀请与您视频通话",
    ID_ADD_EMPTYGROUP:"您所选择的组没有成员，请添加成员或输入内容！",
    ID_SETTING:"个人信息设置",
    ID_CHANGE_PASSWORD:"修改密码",
    ID_CHANGE_PIC:"更改图像",
    ID_UPLOAD_PIC:"请上传图片文件！",
    ID_NUM_INPUT:"请输入正确的手机号，须包含国家码,如中国 0086！",
    ID_EMAIL:"请输入正确的邮箱！",
    ID_SUCCESSFUL:"更改成功！",
    ID_SEND_SUCCESSFUL:"发布成功！",   
    ID_ORG_PASSWORD:"原密码不能为空",
    ID_NEW_PASSWORD:"新密码不能为空",
    ID_PASSWORD_LENGTH:"密码长度不能小于6位",
    ID_PSWD_MATCH:"重复密码不一致",
    ID_ORGPSWD_ERR:"原始密码输入错误",
    ID_CONFIRM_COMPLETE:"你确认要将这条任务设置为完成吗？",
    ID_INFORM_TASK:"设置为完成将通知所有任务成员。",
    ID_DONETASK:"该任务状态已设置为完成！",
    ID_SELETE_OPTION:"请选择投票项！"  ,
    ID_VOTE_COMPLETE:"投票成功，可点击查看投票结果！",
    ID_REFRESH_VOTE:"刷新投票结果",
    ID_REPLY_SUCCESS:"回复成功！",
	ID_REPLY_FAILED:'回复失败',
    ID_UPDATE_TIME:"更新时间",
    ID_NO_RESULT:"没有搜索到任何消息",
    ID_CURRENT_FILE:"当前文件",
    ID_MODERATOR:"主持人",
    ID_SET_MODERATOR:"设为主持人",
    ID_CONNECTING:"正在连接...",
    ID_HANG_UP:"挂断",
    ID_HANGUP_NOTE:"您确认要挂断吗？",
    ID_ATTENDEE:"会议成员",
    ID_MEETING_TOPIC:"会议主题:新会议",
    ID_NEW_MEETING:"新会议",
    ID_MEETING_PERIOD:"会议时长",
    ID_RESTART:"重新发起",
    ID_ENTER_NUM:"输入电话号码/拼音或汉字",
    ID_CALL_NOTE:"会议成员不能少于两位！",
    ID_TOPIC:"会议主题：",
    ID_ONLINE:"在线",
    ID_OFFLINE:"离线",
    ID_REDAIL:"重拨",
    ID_FILENAME:"文件名",
    ID_CO_WORK:"工作协同",
    ID_WEIBO:"微博",
    ID_JOIN_WEIBO:"加入了该微博",
    ID_FILE:"文件",
    ID_CONFERENCE_CALL:"电话会议",
    ID_TASKS:"工作协同",
    ID_QA:"企业百科",
    ID_BALLOT:"集体决策",
    ID_VIDEOCALL:"视频通话",
	ID_VOTE:"投票",
    ID_VOTED:"已投票",
    ID_TICKET:"票",
    ID_NAME:"姓名：",
    ID_EMPLOYEE_NO:"工号：",
    ID_DEPT:"部门：",
    ID_EMAIL2:"邮箱：", 
    ID_PHONE_MOBILE:"手机：",
    ID_PHONE_PSTN:"固话：",
    ID_PHONE_EXTENSION:"分机：",
    ID_PHONE_OTHER:"其他：",
    ID_PHONE_CHOICE:"请选择号码",
    ID_DELETE:"删除", 
	ID_CHOOSEFile:'上传文件',
    ID_TAKE_WORK:"工作协同",
    ID_TAKE_WEIBO:'企业微博',    
    ID_TAKE_VOTE:'集体决策',       
    ID_MAKE_CONF:'视频会议',   
    ID_TEXTING:'Web短信',   
    ID_VOIP:'Web电话',
    ID_FORUM_TITLE:'标题',  
    ID_FORUM_CONTENT:'内容',
    ID_FORUM_REPLY:'输入回复内容',
    ID_FORUM_SUCCESS:"发帖成功！",
	ID_SEARCH_TIP: '直接输入拼音/汉字搜索同事',
    ID_CHARACTER_LEFT:"还能输入",
    ID_CHARACTER_EXCEED:"超出",
    ID_CONFORUM_TIP:'输入内容',
    ID_SUBFORUM_TIP:'不多于200字',
    ID_VIDEO_FREE:'空闲',
    ID_POLLSITEM_IMG:'/images/update_pic.png',
    ID_SEARCH_FOR:'搜索包含',
    ID_SEARCH_ABOUT:'的',
    ID_UPLOAD_TIP:'须小于10M，大文件通过网盘分享',
    ID_FORUM_POST:'发帖',    
    ID_FORUM_FORUMS:'帖子',
    ID_CREATE_GRUOP:'组名不能为空',
    ID_GETMICRO_WRONG:'获取本地媒体失败，摄像头或麦克风不可用',
    ID_VIDEO_RECONNECT:'重新进入',
    ID_VIDEO_CONNECTIP:'是否重新进入该视频会议？',
    ID_VIDEO_TIP:'你有一个视频会议还未结束, 来自：',
    ID_VIDEO_USER: '该用户已被邀请！',
    ID_VIDEO_OFFLINE: '该用户不在线，不能参加视频！',
    ID_VIDEO_ROOM: '会议室已满，没有空位置！',
    ID_VIDEO_Moder: '你不是会议主席，不能邀请！',
    ID_VIDEO_END: '多方视频已结束！',
    ID_VIDEO_EXIT: '已退出多方视频！',
    ID_VIDEO_WAIT:'等待加入',
    ID_P2PVIDEO_FAILED: '发起视频通话失败！',
    ID_P2PVIDEO_ANSWER_FAILED: '接受视频通话失败！',
    ID_P2PVIDEO_ADD_PEER_FIRST: '请先添加对端才能发起视频通话！',
    ID_P2PVIDEO_OVER: '视频通话结束',
    ID_P2PVIDEO_TOO_MANY_PEERS: '视频通话只能添加一个对端！', 
    ID_P2PVIDEO_PEER_REJECTED: '对端未应答您的视频通话请求!', 
    ID_P2PVIDEO_PEER_HOOKON: '对端已结束视频通话！',
    ID_TASKS_SHORTMSG:'该任务包含',
    ID_TASKS_LOGIN:'请登录LWORK手机版查看',
    ID_TASKS_CONTAINERIMG: '图片',  
    ID_TASKS_CONTAINERATTACHE: '附件',    
    ID_REPLY_DIALOG:'查看对话',
    ID_FAVORITE_ALL:'全部',
    ID_VIDEO_ALLOWINVITE:'你确认邀请',   
    ID_VIDEO_JOIN:'加入视频会议吗？',   
    ID_VIDEO_ALLOW:'接受',
    ID_VIDEO_DENY:'拒绝',
    ID_VIDEO_CONFIRM:'视频邀请',
    ID_VIDEO_INVITED1:'来自',
    ID_VIDEO_INVITED2:'如果接受，将结束当前的会议。',
    ID_VIDEO_INVITED3:'如果接受，你将结束退出当前会议。',
    ID_VIDEO_INVITED4:'视频邀请',
    ID_VIDEO_INVITED5:'来自 ',
    ID_VIDEO_INVITED6:'的视频通话呼叫',
    ID_VIDEO_INVITED7:'如果接受，将结束当前视频通话。',
    ID_ADDGROUP_SUCCESS:'添加成功',
    ID_EXT_CONTANTS:'公司外部联系人',
    ID_EXT_ACCOUNT:'输入工号@公司代号',   
    ID_EXT_PHONE:'输入手机号码',  
    ID_EXT_EMAIL:'输入email地址',      
    ID_EXT_ADDED:'该成员已经加入外部联系人列表', 
    ID_EXT_SUCCESS:'成功增加', 
    ID_EXT_ADDNUM:'名外部联系人', 
    ID_EXT_DIALOGTITLE:'增加或修改外部人员信息',
    ID_VOICE_PHONE:'被叫号码格式不对',
    ID_NOTI_TITLE:'桌面提醒',
    ID_NOTI_BTN1:'好的',   
    ID_NOTI_BTN2:'不,谢谢', 
    ID_NOTI_BTN3:'关闭',          
    ID_NOTI_QUS:'您是否需要Lwork桌面提醒功能?',
    ID_NOTI_ICON:'单击地址栏小图标',
    ID_NOTI_SELECT:'在弹出菜单中选择:通知 - 永远在这个网站上执行',
    ID_NOTI_TIP:'及时提醒您来自同事发来的消息和邀请。',
    ID_IM_START_IM:'发送即时消息',
    ID_IM_VIEW_MY_IM:'查看即时消息',
    ID_IM_CREATE_SESSION_FAILED:'创建会话失败！',
    ID_IM_I_INVITE:'我邀请了',
    ID_IM_TO_JOIN_CHAT:'加入聊天',
    ID_IM_ALREADY_IN_SESSION:'已经在当前的会话中！',
    ID_IM_CANT_INVITE_OFFLINES:'不能邀请不在线的用户！',
    ID_IM_I_QUITED:'我已经退出了聊天。',
    ID_IM_CHATROOM:'聊天室',
    ID_IM_SEND_MSG:'发送',
    ID_IM_DIRECT_SEND_TIP:'回车：发送',
    ID_MAIL_CC:'抄送',
    ID_MAIL_SENDER:'发件人',
    ID_MAIL_RECEIVER:'收件人',
    ID_MAIL_LOADING_MAIL_FAILED: '网络原因邮件加载不成功',
    ID_MAIL_LOADING:"正在加载邮件内容，请稍等",
    ID_MAIL_FETCH_LIST:"正在获取邮件列表",
    ID_MAIL_LOGIN_SUCCESS:'邮箱登录成功',
    ID_MAIL_LOGIN_FAIL:'邮箱登录失败',
    ID_MAIL_LOGINING:'邮箱登录中',
    ID_MAIL_SET_TIP:'请设置邮箱',
    ID_MAIL_TRANSFER_ONLY_ONE:"只能选择一封邮件转发",
    ID_MAIL_NEW:'新建便签',
    ID_MAIL_NO_RECEIVER:'未填收件人',
    ID_MAIL_ATTACH_UPLOADING:'附件上传中，请稍后发送',
    ID_MAIL_RECEIVER_TIP:'输入收件人邮箱地址(以;分隔)',
    ID_MAIL_SENDING:'邮件发送中...',
    ID_MAIL_SENT_FAIL_REASON:'邮件发送失败,原因:',
    ID_MAIL_SENT_SUCCESS:'邮件发送成功',
    ID_MAIL_CLOSE_NEW:'要存入草稿箱吗？',
    ID_MAIL_CLOSE_NEW_TIP:"点击确定保存到草稿箱，点击取消将不会保存所有修改",
    ID_REQUEST_ERROR:'服务器繁忙，稍后再试！',
    ID_WRONG_VOIP:'请点击上面“允许”使用媒体按钮。',
    ID_ERROR_PERMISSION:'没有操作权限',
    ID_ERROR_NOBLANCE:'账户余额不足。',
    ID_ERROR_COMNOBLANCE:'企业账户余额不足。',   
    ID_ERROR_NORESOURCE:'没有空闲的会议资源，请稍后再试。' ,
    ID_PREPAR_CALL:'正在初始化媒体...' 

};

function QueryString(uriStr){
  var sea =  (window.location.search).slice(1);
  var str = sea.split('&');
  var query;  
  for(var i =0 ; i < str.length; i++){
    query = str[i].split('=');
	if( query[0] == uriStr ) return query[1] ;
  }
  return ''	
}
var lw_lang ;
QueryString('language') == 'en' ? ( lw_lang = lw_lang_en , $('body, input, textarea').css('font-family','Helvetica, Arial, sans-serif')) : (lw_lang = lw_lang_ch, $('body, input, textarea').css('font-family','"微软雅黑"'));
$('#polls_option').find('.display_img').attr('src', lw_lang.ID_POLLSITEM_IMG)